spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/skingambleur
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: git
  config:
    import: optional:configserver:http://localhost:8888/
