server:
  port: 8030
spring:
  application:
    name: arme
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/skingambleur?authSource=admin
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/