server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
#        native:
#          search-locations:  https://github.com/IsmaelLebrun/bankApplicationConfig
        git:
#          uri: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/IsmaelLebrun/bankApplicationConfig
          clone-on-start: true
          uri: https://github.com/IsmaelLebrun/skingambleurConfig
          default-label: main
  profiles:
    active: git
