spring:
  application:
    name: skins
  profiles:
    active: git
  config:
    import: optional:configserver:http://localhost:8888/
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/